/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railwaycloakroommangement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author prate
 */
public class bookingPage extends javax.swing.JFrame {
 Connection connection = null;
    PreparedStatement prp = null;
    ResultSet result = null;
    DefaultTableModel Table = new DefaultTableModel();
    
    /**
     * Creates new form bookingPage
     */
   
    
    String uid,sid;
    int noOfLoc;
    int pnr;
    public bookingPage() {
        initComponents();
    }
    
    public bookingPage(String userid,String st_id,int pnr) {
        uid = userid;
        sid = st_id;
        this.pnr = pnr;
        
        initComponents();
        Object columns[] = {"Sation id", "No of locker"};
        Table.setColumnIdentifiers(columns);
        jTable2.setModel(Table);
        connection = connector.ConnectDB();
        String sql = "select st_id, no_locker from locker where st_id ='"+st_id+"'";

        try {
            prp = connection.prepareStatement(sql);
            result = prp.executeQuery();

            Object columnData[] = new Object[2];
            while (result.next()) {

               columnData[0] = st_id;
               columnData[1] = noOfLoc= result.getInt("no_locker");

                Table.addRow(columnData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 51,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("BOOK LOCKER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 225, -1));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 16, -1, -1));

        jTable2.setBackground(new java.awt.Color(255, 153, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}

            },
            new String [] {
                "STATION", "NO LOCKER"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 131));

        jTextField1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 71, -1));

        jLabel3.setText("No of locker needed");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 0, 255));
        jButton2.setText("Send request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 550, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/420210.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1909, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bookLocker bl = new bookLocker(uid,pnr);
        bl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                                
    int n = Integer.parseInt(jTextField1.getText());
    String sql = "INSERT INTO transaction (user_id, pnr, station_id, no_of_locker, status) VALUES (?, ?, ?, ?, ?)";
    int Lval = noOfLoc;
    try {
        
//        if(noOfLoc - n >= 0){
//            Lval -= n;
//                
//                String sql2 = "update locker set no_locker =" + Lval + " where st_id='" + sid + "'";
//                String sql3 = "update transaction set status ='Accepted' where pnr='" + pnr + "' and station_id='"+sid+"'";
//                String sql4 = "insert into assigned_locker(station_id,start_time,end_time,no_locker,pnr) values(?,?,?,?,?) ";
//                prp = connection.prepareStatement(sql2);
//                prp.execute();
//                prp = connection.prepareStatement(sql3);
//                prp.execute();
//                
//                prp = connection.prepareStatement(sql4);
//                prp.setString(1, sid);
//                prp.setString(2, "");
//                prp.setString(3, "");
//                prp.setInt(4, n);
//                prp.setInt(5, pnr);
//
//                prp.execute();
//                JOptionPane.showMessageDialog(null, "Accepted" +"d successfully");
//        }
//        else{
        prp = connection.prepareStatement(sql);
        prp.setString(1, uid);
        prp.setInt(2, pnr);
        prp.setString(3, sid);
        prp.setInt(4, n);
        prp.setString(5, "pending");

        int rowsAffected = prp.executeUpdate();

        if (rowsAffected == 0) {
            
            throw new SQLException("Record already exists");
        }

        JOptionPane.showMessageDialog(null, "In waiting list, wait for admins approval");
//        }
    } catch (SQLIntegrityConstraintViolationException e) {
        int errorCode = e.getErrorCode();
        
        if (errorCode == 1062) { 
            JOptionPane.showMessageDialog(null, "Request has already been made through this PNR at the station "+sid);
        } else {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
